In [10]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris

In [11]:
iris = load_iris()
data_frame = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [12]:
data_frame.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [22]:
data_frame.shape

(150, 5)

In [13]:
data_frame.target.unique()

array([0., 1., 2.])

In [14]:
X = data_frame.drop('target', axis=1)
y = data_frame.target

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42) 

In [16]:
# 3 elegir el modelo
from sklearn.tree import DecisionTreeClassifier #importamos el modelo
tree = DecisionTreeClassifier(max_depth=2, random_state=42) #creamos el modelo

In [17]:
#4 entrenar el modelo
tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2, random_state=42)

In [18]:
y_train_pred = tree.predict(X_train) #Prediccion en Train
y_test_pred = tree.predict(X_test) #Prediccion en Test

In [19]:
y_train_pred

array([1., 2., 2., 1., 2., 1., 2., 1., 0., 2., 1., 0., 0., 0., 1., 2., 0.,
       0., 0., 1., 0., 1., 2., 0., 1., 2., 0., 2., 2., 1., 1., 2., 1., 0.,
       1., 2., 0., 0., 1., 2., 0., 2., 0., 0., 2., 1., 2., 2., 2., 2., 1.,
       0., 0., 2., 2., 0., 0., 0., 2., 2., 0., 2., 2., 0., 1., 1., 2., 1.,
       2., 0., 2., 1., 2., 1., 1., 1., 0., 1., 1., 0., 1., 2., 2., 0., 1.,
       2., 2., 0., 2., 0., 2., 2., 2., 1., 2., 1., 1., 2., 2., 0., 1., 1.,
       0., 1., 2.])

In [20]:
y_test_pred

array([1., 0., 2., 1., 2., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0., 0., 0., 1., 0.,
       0., 2., 1., 0., 0., 0., 2., 1., 1., 0., 0.])

In [21]:
#5 testear el modelo

from sklearn.metrics import accuracy_score

#Calculo el accuracy en Train
train_accuracy = accuracy_score(y_train, y_train_pred)

#Calculo el accuracy en Test
test_accuracy = accuracy_score(y_test, y_test_pred)

print('% de aciertos sobre el set de entrenamiento:', train_accuracy)
print('% de aciertos sobre el set de evaluación:',test_accuracy)

% de aciertos sobre el set de entrenamiento: 0.9428571428571428
% de aciertos sobre el set de evaluación: 0.9777777777777777


In [ ]:
# Otro modelo

In [23]:
from sklearn import datasets

dataset = datasets.load_breast_cancer()

In [24]:
#Seleccionamos todas las columnas
X = dataset.data
#Defino los datos correspondientes a las etiquetas
y = dataset.target

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [27]:
#Arbol de decisión
from sklearn.tree import DecisionTreeClassifier
algoritmo = DecisionTreeClassifier(max_depth=2, random_state = 42)

In [28]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2, random_state=42)

In [29]:
#Realizo una predicción
y_train_pred = algoritmo.predict(X_train) #Prediccion en Train
y_test_pred = algoritmo.predict(X_test) #Prediccion en Test

In [30]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_test_pred)
matriz

array([[ 57,   6],
       [  6, 102]])

In [31]:
from sklearn.metrics import accuracy_score

#Calculo el accuracy en Train
train_accuracy = accuracy_score(y_train, y_train_pred)

#Calculo el accuracy en Test
test_accuracy = accuracy_score(y_test, y_test_pred)

print('% de aciertos sobre el set de entrenamiento:', train_accuracy)
print('% de aciertos sobre el set de evaluación:',test_accuracy)

% de aciertos sobre el set de entrenamiento: 0.9422110552763819
% de aciertos sobre el set de evaluación: 0.9298245614035088


In [32]:
data_tennis = pd.read_csv("tennis.csv", sep = ",")

In [33]:
data_tennis

clima temperatura humedad ventoso jugar_tenis
0    soleado    caluroso    alta      no          no
1    soleado    caluroso    alta      si          no
2    nublado    caluroso    alta      no          si
3   lluvioso    templado    alta      no          si
4   lluvioso        frio  normal      no          si
5   lluvioso        frio  normal      si          no
6    nublado        frio  normal      si          si
7    soleado    templado    alta      no          no
8    soleado        frio  normal      no          si
9   lluvioso    templado  normal      no          si
10   soleado    templado  normal      si          si
11   nublado    templado    alta      si          si
12   nublado    caluroso  normal      no          si
13  lluvioso    templado    alta      si          no

In [34]:
data_tennis.shape

(14, 5)

In [35]:
data_tennis.count()

clima          14
temperatura    14
humedad        14
ventoso        14
jugar_tenis    14
dtype: int64

In [56]:
data_tennis.dtypes

clima          object
temperatura    object
humedad        object
ventoso        object
jugar_tenis    object
dtype: object

In [73]:
data_tennis_dummy = pd.get_dummies(data_tennis, drop_first=True)

In [74]:
data_tennis_dummy

clima_nublado  clima_soleado  temperatura_frio  temperatura_templado  \
0               0              1                 0                     0   
1               0              1                 0                     0   
2               1              0                 0                     0   
3               0              0                 0                     1   
4               0              0                 1                     0   
5               0              0                 1                     0   
6               1              0                 1                     0   
7               0              1                 0                     1   
8               0              1                 1                     0   
9               0              0                 0                     1   
10              0              1                 0                     1   
11              1              0                 0                     1   
12              1              0                 0                     0   
13              0              0                 0                     1   

    humedad_normal  ventoso_si  jugar_tenis_si  
0                0           0               0  
1                0           1               0  
2                0           0               1  
3                0           0               1  
4                1           0               1  
5                1           1               0  
6                1           1               1  
7                0           0               0  
8                1           0               1  
9                1           0               1  
10               1           1               1  
11               0           1               1  
12               1           0               1  
13               0           1               0

In [75]:
#Separamos los datos de entrada de la salida
X = data_tennis_dummy.drop('jugar_tenis_si', axis=1) #Elimino de mi dataset la variable a predecir
y = data_tennis_dummy.jugar_tenis_si #Defino el Target

In [76]:
from sklearn.model_selection import train_test_split #Importamos la libreria para separar en train y test

#Me quedo con 30% para test y 70% para train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30) 

In [77]:
from sklearn.tree import DecisionTreeClassifier #Importamos el modelo
tree = DecisionTreeClassifier(max_depth=2) #Creamos el modelo

In [78]:
#Entrenamos el modelo
tree.fit(X_train,y_train) #Entrenamos el modelo

DecisionTreeClassifier(max_depth=2)

In [79]:
y_train_pred = tree.predict(X_train) #Prediccion en Train
y_test_pred = tree.predict(X_test) #Prediccion en Test

In [80]:
from sklearn.metrics import accuracy_score

#Calculo el accuracy en Train
train_accuracy = accuracy_score(y_train, y_train_pred)

#Calculo el accuracy en Test
test_accuracy = accuracy_score(y_test, y_test_pred)

print('% de aciertos sobre el set de entrenamiento:', train_accuracy)
print('% de aciertos sobre el set de evaluación:',test_accuracy)

% de aciertos sobre el set de entrenamiento: 1.0
% de aciertos sobre el set de evaluación: 0.6
